# permissions for end users to view vkhellooperators.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: vkhellooperator-viewer-role
rules:
- apiGroups:
  - cache.example.com
  resources:
  - vkhellooperators
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cache.example.com
  resources:
  - vkhellooperators/status
  verbs:
  - get
